name: system_time_change_detector
description: "This plugin allows to detect timezone / time changes via Flutter desktop apps."
version: 0.0.4
homepage: https://github.com/prabhuc94/SystemTimeChangeDetector

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  plugin:
    platforms:
      linux:
        pluginClass: SystemTimeChangeDetectorPlugin
      macos:
        pluginClass: SystemTimeChangeDetectorPlugin
      windows:
        pluginClass: SystemTimeChangeDetectorPluginCApi
